### ISSUE TITLE
Online deployment of grunt

### ISSUE THREAD

**Issue by KleanOcean** [Esri/building-viewer#6]
Hi, the work is awesome! How can we deploy this project to web? I currently failed numerous times using Heroku, any advice to deploy this project?

**Comment by arnofiva** [comment]
Thanks for the feedback, glad you like it! Did you manage to get it working? The project consists of static files only, it would be interesting to know what caused problems deploying to Heroku.

**Comment by KleanOcean** [comment]
Hi, the problem resolved, just minor problem. By the way, your project is
awesome!

Arno Fiva <notifications@github.com> 於 2021年1月29日週五 下午8:23寫道：

**Comment by KleanOcean** [comment]
Hi,

I have another question for this project. How to link photo to the floor
plan in the floor by floor section? I have made a feature layer with some
polygon lines, and add required attributes on it, but still cant click the
red polygon to open image. Is there any document or sample file that we can
follow on configurating the feature layers? I have attached my feature
layer and some screenshots for better understanding.

link:
https://thkust.maps.arcgis.com/home/item.html?id=549a2d3c510d4ed589c89c87de6a8f28#overview

Thanks,
Raymond Or

>

**Comment by arnofiva** [comment]
Hi, apologies for the late answer.. I would like to help but unable to check your feature layer. Can you share it with me? My ArcGIS Online username is `arnofiva_zurich`. Thanks!

**Comment by KleanOcean** [comment]
Hi Arno, thanks a lot!

The feature layer link is public :
https://thkust.maps.arcgis.com/home/item.html?id=931d67cf6ae04d54bfd8120e5d63dc4a#overview
or this url :
https://services2.arcgis.com/oss2UMGxOjWzXjo4/arcgis/rest/services/Floor_pictures/FeatureServer
after I added it to the webscence and ran the server, in the "Floor by
floor" section, a continuous error came out.



Arno Fiva <notifications@github.com> 於 2021年2月22日週一 上午5:23寫道：

**Comment by KleanOcean** [comment]
Hi Arno, the problem is resolved, thanks

or kaming <orkaming@gmail.com> 於 2021年2月22日週一 下午7:42寫道：

**Comment by harmondsantos** [comment]
Hi, this is really awesome! Thanks for sharing this.
I have tried this and everything works except for the building scene layer filtering. I'm on Enterprise 10.7.1, which doesn't have the floor picker capability on the scene viewer. Could that be the reason why the BSL doesn't filter? Thanks!
